### ISSUE TITLE
`UnsupportedInstruction`: encountered an LLVM instruction which is not currently supported: terminator Invoke

### ISSUE THREAD

**Issue by ctz** [PLSysSec/haybale#1]
Hello,

I'm just playing around with this and seem to have got stuck.  My code:

```rust
use std::path::Path;
use haybale;
use rustc_demangle::demangle;

fn main() {
    let proj = haybale::Project::from_bc_path(&Path::new("../rustls-llvm8.bc"))
        .expect("cannot open bitcode");
    for (func, _module) in proj.all_functions() {
        if demangle(&func.name).to_string() == "<rustls::client::tls12::ExpectServerDone as rustls::client::hs::State>::handle::h9460148ae7f0b07f" {
            println!("func {:?} ret {:?} param {:#?}", demangle(&func.name), func.return_type, func.parameters);

            for (i, bb) in func.basic_blocks.iter().enumerate() {
                println!("bb {}: {:?}", i, bb);
            }

            let mut cfg = haybale::Config::<haybale::backend::BtorBackend>::default();
            cfg.null_detection = false;
            let mut em = haybale::symex_function(&func.name,
                                                 &proj,
                                                 cfg);

            loop {
                let n = em.next();
                if n.is_none() {
                    break;
                }
                println!("n {:?}", n);
                let st = em.state();
                println!("state 0 {:?}", st.cur_loc);
            }


        }
    }
}

```

I've attached my input file.

This produces an error:

```
n Some(Err("Received the following error:\n  `UnsupportedInstruction`: encountered an LLVM instruction which is not currently supported: terminator Invoke(Invoke { function: Right(ConstantOperand(GlobalReference { name: Name(\"_ZN6rustls7hash_hs13HandshakeHash11add_message17h8f65251448a5a012E\"), ty: FuncType { result_type: PointerType { pointee_type: NamedStructType { name: \"hash_hs::HandshakeHash\", ty: Some((Weak)) }, addr_space: 0 }, param_types: [PointerType { pointee_type: NamedStructType { name: \"hash_hs::HandshakeHash\", ty: Some((Weak)) }, addr_space: 0 }, PointerType { pointee_type: NamedStructType { name: \"msgs::message::Message\", ty: Some((Weak)) }, addr_space: 0 }], is_var_arg: false } })), arguments: [(LocalOperand { name: Number(7), ty: PointerType { pointee_type: NamedStructType { name: \"hash_hs::HandshakeHash\", ty: Some((Weak)) }, addr_space: 0 } }, [EnumAttribute { kind: 1, value: Some(8) }, EnumAttribute { kind: 9, value: Some(256) }]), (LocalOperand { name: Number(3), ty: PointerType { pointee_type: NamedStructType { name: \"msgs::message::Message\", ty: Some((Weak)) }, addr_space: 0 } }, [EnumAttribute { kind: 20, value: None }, EnumAttribute { kind: 37, value: None }, EnumAttribute { kind: 1, value: Some(8) }, EnumAttribute { kind: 9, value: Some(184) }])], return_attributes: [EnumAttribute { kind: 1, value: Some(8) }, EnumAttribute { kind: 9, value: Some(256) }], result: Number(8), return_label: Name(\"bb1\"), exception_label: Name(\"cleanup\"), function_attributes: [], calling_convention: C })\nLLVM backtrace:\n  #1: {../rustls-llvm8.bc: _ZN85_$LT$rustls..client..tls12..ExpectServerDone$u20$as$u20$rustls..client..hs..State$GT$6handle17h9460148ae7f0b07fE \"start\", instr 137}\n\n"))
```

Which I think originates from https://github.com/PLSysSec/haybale/blob/master/src/symex.rs#L191 when there's a function invocation in basic block tail position? Is there any plan to support that case?

**Comment by ctz** [comment]
[rustls-llvm8.zip](https://github.com/PLSysSec/haybale/files/4006122/rustls-llvm8.zip)

**Comment by cdisselkoen** [comment]
Hi, sorry for the late response, was traveling for the holidays.  You're completely right that `haybale` doesn't currently support the LLVM `invoke` instruction - I simply haven't encountered it yet in any of my test cases or other code that I've analyzed with haybale.  I should be able to add support for `invoke` in the next couple of days.

Glad to see you're interested in this project!

**Comment by cdisselkoen** [comment]
Do you happen to have a minimal Rust example that results in LLVM `invoke` / `resume` instructions?  Or know under what conditions `rustc` emits those instructions?  Mostly for the purposes of constructing a compact test case(s) for invoke/resume functionality.

**Comment by cdisselkoen** [comment]
As of commit `98ac0af`, `haybale` master now has support for LLVM `invoke`/`resume`, and a number of test cases involving C++ exceptions.  The functionality does have some flaws at the moment, particularly surrounding the matching of catch blocks to exceptions, but these should only result in exploring additional paths which shouldn't be valid, under some circumstances.  All valid paths should still be found and reported correctly.  Let me know if this support is sufficient for your uses of `invoke`/`resume`, or if there are still problems (which is very possible)!

I'd still love to have a concise Rust testcase for `invoke`/`resume` if you have one or know how to get one.

**Comment by cdisselkoen** [comment]
Also, if you're interested, commit `a15f0b2` just added built-in support for Rust panics, which seems to be relevant for your input file.

**Comment by cdisselkoen** [comment]
I'm going to go ahead and close this as addressed in the commits mentioned above and in `haybale` crate version 0.2.0 (released January 8).  You might also be interested in some of the other changes made in 0.2.0 and beyond; see the Changelog in the README.  If you have other questions or issues, feel free to reopen this or another issue.  Thanks again for your interest!
