### ISSUE TITLE
eBPF code input

### ISSUE THREAD

**Issue by radustoenescu** [PLSysSec/haybale#14]
I tried running `haybale` on [eBPF](https://ebpf.io/) code and I get:

`error: file doesn't start with bitcode header`

I'm guessing some `eBPF` intrinsics are causing this.

The input code is sourced using:

`clang-10 -S -target bpf -g -O2 -Wall -Wno-unused-value -Wno-pointer-sign -Wno-compare-distinct-pointer-types -Werror -emit-llvm -c -I libbpf/include -I headers/ xdp_kern.c -o xdp_kern.bc`

Since I didn't find any other means of reaching the community, I've two questions regarding this, that I'll leave here:

1. Does `haybale` support eBPF?
2. If so, how should I tackle the above problem?

**Comment by cdisselkoen** [comment]
I see that your command-line includes both `-S` and `-c`.  Can you try removing the `-S`?

Alternately, can you try opening your `xdp_kern.bc` in a text editor?  If it's legible text, then you actually have an LLVM assembly file (typically `.ll`), and you can use `llvm-as` (distributed with LLVM) to convert it to a `.bc` file.

**Comment by cdisselkoen** [comment]
I'm going to assume this is resolved -- feel free to open another issue if you have more questions.
