### ISSUE TITLE
rust version 1.51.0 can't compile haybale 

### ISSUE THREAD

**Issue by YuXinFan** [PLSysSec/haybale#16]
It's just a tip for new users:
After updating rust to 1.51.0, haybale version 0.6.3 can't be compiled.
But haybale works well at rust 1.50.0
It seems caused by rust's backward incompatibility.

**Comment by cdisselkoen** [comment]
A couple days ago I filed an issue with one of haybale's dependencies (https://github.com/dtolnay/reduce/issues/4) hoping they would resolve this.  Since they haven't responded yet, I may just put in a workaround on haybale's side so that it can compile with both 1.50 and 1.51.

**Comment by cdisselkoen** [comment]
Fixed and released `haybale` version 0.6.4.
