### ISSUE TITLE
Are there any methods provided by haybale for constraining certain variables?

### ISSUE THREAD

**Issue by Just1ceP4rtn3r** [PLSysSec/haybale#19]
e.g.

```
int foo(struct Context* context) {
  //assert(context->x == 1);
  if (context->x == 0)
     return 0;
  
  if (context->y < 0)
     return -1;
  else 
     return 1;
} 

```

So I just want to take "context->y" as a symbolic value and restrict "context->x" to 1. Can we reach this but not modify the origin LLVM IR ?

**Comment by Just1ceP4rtn3r** [comment]
I found that `symex_function` provides a parameter named "params: Option<Vec<ParameterVal>>". But how to set some initial value for a pointer of struct?

**Comment by cdisselkoen** [comment]
One way to do this is: 
1. use `symex_function` with `params=None` to get an `ExecutionManager`
2. use [`ExecutionManager::mut_state()`](https://docs.rs/haybale/latest/haybale/struct.ExecutionManager.html#method.mut_state) to access the `State`, from which you can [`allocate`](https://docs.rs/haybale/latest/haybale/struct.State.html#method.allocate) some bits representing the `struct Context` you want to pass in, receiving a `BV` pointer to the new allocation
3. constrain the `x` field of that allocation to be 1
2. finally, use `ExecutionManager::param_bvs()` to access the `context` parameter, and then constrain it to be equal to the pointer received in step 2.

For a more thorough solution, you can take a look at what [`pitchfork`](https://github.com/PLSysSec/haybale-pitchfork/blob/main/README.md) built on top of `haybale`, in particular `pitchfork`'s `AbstractData`.

**Comment by Just1ceP4rtn3r** [comment]
Hello, thanks for your explanation!
But I still have some difficulties achieving my goal with the first way above, here is my code, and "struct Context *" is the type of parameter I want to pass to the function to be analyzed.

  1. use `State.allocate` to create a constant BV that represents  "struct Context *" to be passed to the function. 
  2. create an unconstraint  BV representing the "struct Context" and constrain the `x` field to be 1

Can you help me that how to get `contextPtr` and `context` together? 
Thanks!

```
'''
struct Context{
    char a;
    char b;
    char x;
    char y;
}
'''

let project = get_project();
let mut x: ExecutionManager<haybale::backend::DefaultBackend> =
    symex_function(f, &project, myConfig, None).unwrap();
let mut mutState = x.mut_state();

// allocate: struct Context *
let mut contextPtr = mutState.allocate(64 as u64);

// constrain context.x to be 48
// contextBV shift left by 16 bits then shift right by 24 bits
let context = BV::new(&mutState.solver, struct_size_bits, None);
let mut constraintX =
    context.sll(&mutState.bv_from_u64(&mutState.solver, 16, struct_size_bits));
constraintX =
    constraintX.srl(&mutState.bv_from_u64(&mutState.solver, 24, struct_size_bits));
constraintX
    ._eq(&mutState.bv_from_u64(48, struct_size_bits))
    .assert()?;
```

**Comment by cdisselkoen** [comment]
You can do
```rust
let context_inmem = mutState.read(&contextPtr, struct_size_bits).unwrap();
context_inmem._eq(&context).assert().unwrap();
```
Or, even better, just constrain the `x` field of `context_inmem` directly, without creating a separate BV:
```rust
let context = mutState.read(&contextPtr, struct_size_bits).unwrap();  // instead of BV::new
// use `context` as in the above comment
```

**Comment by Just1ceP4rtn3r** [comment]
Yeah, I understand, thanks! But Haybale throw errors `Error::NullPointerDereference` because we didn't allocate other fields of the struct like `next`:
```
struct Context{
    struct Context * next;
    char a;
    char b;
    char x;
    char y;
}
```

Is necessary for us  to allocate all the fields for that struct (`Context`)?

**Comment by cdisselkoen** [comment]
Sorry for the delayed response (to this and the other thread) -- a lot on my plate right now.

Yes, you will have to initialize those other fields if you want Haybale to consider specific values for them.  If you don't initialize them, Haybale will consider that memory to be unconstrained, i.e., could have any value, including NULL, hence the null pointer error.

For null pointer errors specifically, you may want to configure `Config.null_pointer_checking` instead; this has a few different options for how Haybale treats and reports possible null pointer dereferences.

**Comment by Just1ceP4rtn3r** [comment]
Haha, no problem. Then I need to initialize those fields. Otherwise, not only it will lead to the null pointer error, but also may consume a large of time to solve constraints. Thanks!
