### ISSUE TITLE
Trouble analyzing basic Rust programs

### ISSUE THREAD

**Issue by hudson-ayers** [PLSysSec/haybale#4]
Hi, I am interested in using this tool for analyzing Rust source code. However I have found I am unable to use either example analysis on even an extremely simple rust program:

The program I am analyzing, compiled to bitcode using `cargo rustc -- -g --emit=llvm-bc --emit=llvm-ir`: 
```rust
fn ez(input: u32) -> u32 {
    input * 2
}

fn main() {
    let out = ez(1);
    println!("out: {}", out);
}
```

My haybale code (in a separate repository):
```rust
use haybale::*;
use std::path::Path;
use std::result::Result;
use std::string::String;

fn main() -> Result<(), String> {
    let project = Project::from_bc_path(&Path::new("/home/hudsonayers/test2/target/debug/deps/test2-ad7a69efa56795e2.bc"))?;
    let ret = get_possible_return_values_of_func("ez", vec!(Some(1)), &project, Config::default(), None, 10);
    println!("ret: {:?}", ret);
    /*match find_zero_of_func("ez", &project, Config::default()) {
        Ok(None) => println!("foo can never return 0"),
        Ok(Some(inputs)) => println!("returns 0 for: {:?}", inputs),
        Err(e) => panic!("{}", e),
    }*/
    Ok(())
}
```
This code compiles, but fails when run. 

The output I get:
```
thread 'main' panicked at '`FunctionNotFound`: encountered a call of a function named "llvm.expect.i1", but failed to find an LLVM definition, a function hook, or a built-in handler for it

Backtrace:
  #1: {/home/hudsonayers/test2/target/debug/deps/test2-ad7a69efa56795e2.bc: ez, bb "start", instr 7}
         (/home/hudsonayers/test2/src/main.rs, line 3, col 4)
```

I get the same result if I call `find_zero_of_func()` instead. The code runs fine if I just construct the project but do not use it.

Both repositories are using rust 1.40.0 (also tried later versions). I have boolector 3.1.0 installed. I am using llvm 9, installed per the instructions at https://apt.llvm.org/ . My machine is running debian 10, though I also tried on an ubuntu 20.04 machine with equivalent results.

Any advice? Is this an issue with my llvm installation? Something else I am missing?

Thanks in advance.

**Comment by cdisselkoen** [comment]
Hmm, this is weird.  It's not your fault at all, but rather that Haybale doesn't yet have support for the [`llvm.expect` intrinsic](https://releases.llvm.org/9.0.0/docs/LangRef.html#llvm-expect-intrinsic), which is essentially a no-op for Haybale's purposes.  The weird part is why this hasn't caused problems before.  Even one of the files in Haybale's test suite contains a call to `llvm.expect`, the test just doesn't exercise the function that contains it.

The patch for this should be really easy, and I'll do that right now.  Sorry about your experience with this!

**Comment by cdisselkoen** [comment]
^ Let me know if that commit fixes your issue!  I also added your simple example as a test case for Haybale.

**Comment by hudson-ayers** [comment]
This has resolved my issue! Thank you so much for the prompt response and fix. I will let you know if anything else comes up as I move towards using haybale on more complex functions.
