### ISSUE TITLE
Viewing path through non-inlined function in another crate

### ISSUE THREAD

**Issue by hudson-ayers** [PLSysSec/haybale#5]
Hi,

I have been using `execution_manager.state().get_path()` to parse the instruction path taken by a single symbolic execution of a function. However, I have found that if a function includes cross-crate function calls (even if the crates are in the same workspace), that the execution within the function is not included in the returned path. Is there a way to view the path taken through a function in a different crate from the function being analyzed?

I have found that marking the function as `#[inline(always)]` works, but I do not want to have this requirement.

Here is some example code to illustrate my issue.

File being analyzed:
```rust
use othercrate::not_inlined;

#[no_mangle]
fn two_paths(a: u8) -> u8 {
    if a < 25 {
        a + 3
    } else {
        let mut tmp = a + 2;
        tmp *= 3;
        not_inlined(tmp - 7)
    }
}
```

Function defined in another crate:
```rust
#[inline(never)]
pub fn not_inlined(input: u8) -> u8 {
    let mut input = input;
    let mut iterations = 0;
    while input != 0 {
        iterations += 1;
        input = if input % 4 == 1 {
            (input + 4) % 3
        } else if input % 3 == 2 {
            (input + 2) % 5
        } else {
            (input + 3) % 7
        };
    }
    iterations
}
```

Haybale code:
```rust
/// Print all LLVM IR instructions in a given symbolic execution
pub fn print_instrs<'p>(path: &Vec<PathEntry<'p>>) {
    for entry in path {
        let location = &entry.0;
        match location.instr {
            BBInstrIndex::Instr(idx) => {
                for instr in location.bb.instrs.iter().skip(idx) {
                    println!("instruction: {:?}", instr);
                }
            }
            BBInstrIndex::Terminator => println!("Terminator."),
        }
    }
}


fn main() -> Result<(), String> {
    //...
    let project = Project::from_bc_path(&path)?;
    let mut em: ExecutionManager<BtorBackend> = symex_function(funcname, project, config);
    em.next();
    let state = em.state();
    print_instrs(state.get_path());
```

If I run this as written with `not_inlined()` in another crate, the output is as follows:
```
instruction: ICmp(ICmp { predicate: ULT, operand0: LocalOperand { name: Name("a"), ty: IntegerType { bits: 8 } }, operand1: ConstantOperand(Int { bits: 8, value: 25 }), dest: Name("_2"), debugloc: None })
instruction: Mul(Mul { operand0: LocalOperand { name: Name("a"), ty: IntegerType { bits: 8 } }, operand1: ConstantOperand(Int { bits: 8, value: 3 }), dest: Number(0), debugloc: None })
instruction: Add(Add { operand0: LocalOperand { name: Number(0), ty: IntegerType { bits: 8 } }, operand1: ConstantOperand(Int { bits: 8, value: 255 }), dest: Name("_7"), debugloc: None })
instruction: Call(Call { function: Right(ConstantOperand(GlobalReference { name: Name("_ZN3tmp5stuff12not_too_long17h9dcf6846dc92353cE"), ty: FuncType { result_type: IntegerType { bits: 8 }, param_types: [IntegerType { bits: 8 }], is_var_arg: false } })), arguments: [(LocalOperand { name: Name("_7"), ty: IntegerType { bits: 8 } }, [])], return_attributes: [], dest: Some(Number(1)), function_attributes: [], is_tail_call: true, calling_convention: C, debugloc: None })
```

As you can see, there are no instructions after the function call. However if I move the code to a file in the same crate as `two_paths()`, this is the (truncated) output:
```
instruction: ICmp(ICmp { predicate: ULT, operand0: LocalOperand { name: Name("a"), ty: IntegerType { bits: 8 } }, operand1: ConstantOperand(Int { bits: 8, value: 25 }), dest: Name("_2"), debugloc: None })
instruction: Mul(Mul { operand0: LocalOperand { name: Name("a"), ty: IntegerType { bits: 8 } }, operand1: ConstantOperand(Int { bits: 8, value: 3 }), dest: Number(0), debugloc: None })
instruction: Add(Add { operand0: LocalOperand { name: Number(0), ty: IntegerType { bits: 8 } }, operand1: ConstantOperand(Int { bits: 8, value: 255 }), dest: Name("_7"), debugloc: None })
instruction: Call(Call { function: Right(ConstantOperand(GlobalReference { name: Name("_ZN12haybale_test5stuff11not_inlined17hf8de0e1e8ce05140E"), ty: FuncType { result_type: IntegerType { bits: 8 }, param_types: [IntegerType { bits: 8 }], is_var_arg: false } })), arguments: [(LocalOperand { name: Name("_7"), ty: IntegerType { bits: 8 } }, [])], return_attributes: [], dest: Some(Number(1)), function_attributes: [], is_tail_call: true, calling_convention: Fast, debugloc: None })
instruction: ICmp(ICmp { predicate: EQ, operand0: LocalOperand { name: Name("input"), ty: IntegerType { bits: 8 } }, operand1: ConstantOperand(Int { bits: 8, value: 0 }), dest: Name("_45"), debugloc: None })
instruction: Phi(Phi { incoming_values: [(LocalOperand { name: Number(1), ty: IntegerType { bits: 8 } }, Name("bb9")), (LocalOperand { name: Name("input"), ty: IntegerType { bits: 8 } }, Name("start"))], dest: Name("input1.07"), to_type: IntegerType { bits: 8 }, debugloc: None })
instruction: Phi(Phi { incoming_values: [(LocalOperand { name: Number(0), ty: IntegerType { bits: 8 } }, Name("bb9")), (ConstantOperand(Int { bits: 8, value: 0 }), Name("start"))], dest: Name("iterations.06"), to_type: IntegerType { bits: 8 }, debugloc: None })
instruction: Add(Add { operand0: LocalOperand { name: Name("iterations.06"), ty: IntegerType { bits: 8 } }, operand1: ConstantOperand(Int { bits: 8, value: 1 }), dest: Number(0), debugloc: None })
instruction: And(And { operand0: LocalOperand { name: Name("input1.07"), ty: IntegerType { bits: 8 } }, operand1: ConstantOperand(Int { bits: 8, value: 3 }), dest: Name("_8"), debugloc: None })
instruction: ICmp(ICmp { predicate: EQ, operand0: LocalOperand { name: Name("_8"), ty: IntegerType { bits: 8 } }, operand1: ConstantOperand(Int { bits: 8, value: 1 }), dest: Name("_7"), debugloc: None })
instruction: URem(URem { operand0: LocalOperand { name: Name("input1.07"), ty: IntegerType { bits: 8 } }, operand1: ConstantOperand(Int { bits: 8, value: 3 }), dest: Name("_13"), debugloc: None })
...
```

In this case, the llvm instructions from within the called function are present. Any recommendation on how I can make sure that these are included even in multi-crate analyses?

Thanks in advance! Sorry for the long post.

**Comment by cdisselkoen** [comment]
Are you adding `.bc` files for both crates to the `Project`?  (See [`Project::add_bc_path()`](https://plsyssec.github.io/haybale/haybale/struct.Project.html#method.add_bc_path) or [`Project::from_bc_dir()`](https://plsyssec.github.io/haybale/haybale/struct.Project.html#method.from_bc_dir).)  I'm wondering if `em.next()` might be returning errors which you're not catching - in particular, a [`FunctionNotFound`](https://plsyssec.github.io/haybale/haybale/enum.Error.html#variant.FunctionNotFound) error for `not_inlined()`.  In the inlined case, I would imagine the code ends up in a single `.bc` file?

Also, btw, there are the functions [`state.pretty_path_llvm()`](https://plsyssec.github.io/haybale/haybale/struct.State.html#method.pretty_path_llvm), [`state.pretty_path_source()`](https://plsyssec.github.io/haybale/haybale/struct.State.html#method.pretty_path_source), and [`state.pretty_path_interleaved()`](https://plsyssec.github.io/haybale/haybale/struct.State.html#method.pretty_path_interleaved) if you're interested in (arguably) prettier displays of a path.  The `print_instrs()` function in your example might not quite do what you want if e.g. there are multiple calls in the same basic block, in which case the symbolic execution might not go directly from `idx` through directly to the end of the block.  Alternately, to print each instruction as it is processed you could consider adding an instruction callback to [`config.callbacks`](https://plsyssec.github.io/haybale/haybale/config/struct.Config.html#structfield.callbacks).

**Comment by cdisselkoen** [comment]
(You could use something like this in place of `em.next()`:
```rust
match em.next().unwrap() {
    Some(_) => {}
    Err(e) => return Err(em.state().full_error_message_with_context(e));
});
```

**Comment by hudson-ayers** [comment]
> Are you adding `.bc` files for both crates to the `Project`? (See [`Project::add_bc_path()`](https://plsyssec.github.io/haybale/haybale/struct.Project.html#method.add_bc_path) or [`Project::from_bc_dir()`](https://plsyssec.github.io/haybale/haybale/struct.Project.html#method.from_bc_dir).) I'm wondering if `em.next()` might be returning errors which you're not catching - in particular, a [`FunctionNotFound`](https://plsyssec.github.io/haybale/haybale/enum.Error.html#variant.FunctionNotFound) error for `not_inlined()`. In the inlined case, I would imagine the code ends up in a single `.bc` file?

Ah, I thought that disabling incremental compilation would always put all of the .bc into a single file, but it turns out that is not the case! Thank you for the tip, I now have that working.

> Also, btw, there are the functions [`state.pretty_path_llvm()`](https://plsyssec.github.io/haybale/haybale/struct.State.html#method.pretty_path_llvm), [`state.pretty_path_source()`](https://plsyssec.github.io/haybale/haybale/struct.State.html#method.pretty_path_source), and [`state.pretty_path_interleaved()`](https://plsyssec.github.io/haybale/haybale/struct.State.html#method.pretty_path_interleaved) if you're interested in (arguably) prettier displays of a path. The `print_instrs()` function in your example might not quite do what you want if e.g. there are multiple calls in the same basic block, in which case the symbolic execution might not go directly from `idx` through directly to the end of the block. Alternately, to print each instruction as it is processed you could consider adding an instruction callback to [`config.callbacks`](https://plsyssec.github.io/haybale/haybale/config/struct.Config.html#structfield.callbacks).

My problem with `pretty_path_llvm()` and similar is that they only print the basic blocks, but not the instructions therein. I did not consider the case of multiple function calls within a basic block, I assumed that a call would always be the last instruction in a given basic block. I will take a look at adding instruction callbacks instead.

To give a bit of a zoomed out view of what I am doing, I am using haybale to find longest paths (in LLVM IR instructions) through functions.

**Comment by cdisselkoen** [comment]
Glad your example is now working!

In LLVM, calls never end basic blocks - they are not terminator instructions.  (A number of things in Haybale would be a little easier if calls were terminators, haha.)

An instruction callback also may not be quite the right thing for your use case.  In particular, when Haybale gets another path, it starts from the longest common prefix with the previous path, and only executes the instructions after that.  So you won't get callbacks for the instructions in the first part of the path if Haybale has executed that before for a previous path.

Briefly brainstorming this, you may want to first go through the `Function` from the `Project` and make a map of basic blocks to instruction counts.  Then you can use the basic-block path to approximate instruction counts.  In the presence of calls, the basic block with the call appears twice in the path (once for the top of the block and once when it returns from the call) so you might have to special-case that, but that's one possible approach.

**Comment by cdisselkoen** [comment]
I'm going to go ahead and close this issue; feel free to reopen this or another issue if you have more questions.

**Comment by hudson-ayers** [comment]
Hi Craig, I'm just coming back to this. I think I am a little confused about how the existing path printing works.

`state::pretty_path_llvm()` seems to iterate through each `PathEntry` and prints the basic block number and instruction number within that basic block where execution began. This makes sense, but in light of calls not ending basic blocks, I am a little confused.

Say the following basic block is bb1:
```
<result> = mul i32 4, %var   
%retval = call i32 @test(i32 %argc)
call i32 (i8*, ...)* @printf(i8* %msg, i32 12, i8 42)  
<result> = mul i32 4, %var   
; some terminator
```

This basic block would be printed as a single entry in the path, something like "bb1, instr 0"

However, the contents of the "test" and "printf" functions also need to be included in the path. Assuming the path taken through test and printf each contain multiple basic blocks, how would those `PathEntry`'s in the `Path`? What about basic blocks for functions called within those functions?

Is it safe to assume that the path contains every basic block in the symbolically executed path exactly the number of times that basic block was executed? (I realize that different executions of the basic block might start at different points, but that would be reflected in the `PathEntry`). Or are basic blocks hidden behind calls not included in the Path?

**Comment by cdisselkoen** [comment]
There are two cases here - one where Haybale executes a _hook_ for the called function(s), and one where Haybale actually executes the called function(s).

Hooked functions don't (currently) appear in the `Path`.  So if these functions are hooked, then this basic block looks the same on the `Path` as one that contains no calls.

Executed functions do (currently) appear in the `Path`.  Let's suppose that in your example, `test` has a single basic block "1", `printf` is hooked, and that your example is from basic block "2" in function "caller".  Then the resulting `Path` should look like this:
```
caller, bb 2, inst 0
test, bb 1, inst 0
caller, bb 2, inst 3
```
If you'd rather that last entry not be included, then I think you should be able to just filter out all the `PathEntry`s that don't have `instr == 0`.

More complicated, let's suppose `test` has 4 basic blocks such that basic block 0 branches to basic block 3 or 7; basic block 3 and 7 each go to basic block 11; and basic block 7 contains a call to the function `inner` which has a single basic block.  Then we'll get two `Path`s:
```
// path 1
caller, bb 2, inst 0
test, bb 0, inst 0
test, bb 3, inst 0
test, bb 11, inst 0
caller, bb 2, inst 3

// path 2
caller, bb 2, inst 0
test, bb 0, inst 0
test, bb 7, inst 0
inner, bb 1, inst 0
test, bb 7, inst 6
test, bb 11, inst 0
caller, bb 2, inst 3
```

I'm not sure if that answers your question?

> Is it safe to assume that the path contains every basic block in the symbolically executed path exactly the number of times that basic block was executed?

This question is hard to answer because of how only part of a basic block might be executed at a time.  Suppose that we have the same example, but now `test` basic block `3` actually panics.  The first `Path` would be
```
caller, bb 2, inst 0
test, bb 0, inst 0
test, bb 3, inst 0
```
and we actually didn't finish executing all of `caller` bb 2.
But in the example paths given above (without the panic), there are two entries for `caller` bb 2 (representing the two "halves" of it) even though it was only executed once.  It might make sense to consider `caller` bb 2 insts 0-2 as one "block" and `caller` bb 2 insts 3+ as another "block".  In that case, each of these "blocks" occurs in the `Path` exactly the number of times that "block" was executed.

> Or are basic blocks hidden behind calls not included in the Path?

All calls are always included in the Path, except calls which are hooked.  (We can't include hooked calls, because for instance, we may not even know how many basic blocks are in the called function -- we may not have LLVM bitcode for the called function.)

**Comment by hudson-ayers** [comment]
Thanks for this explanation, its extremely helpful. For my use case, I already ignore paths which panic (or exit), so it seems that ignoring `PathEntry`'s which don't have `inst==0` should be sufficient. Also, my codebase has no dynamic allocation, so I really should not be using any of the function hooks.

I plan to write a helper function which, given a `Path`, prints all instructions in that Path in the order they were executed -- under the assumption that no panics/exceptions occurred in the Path under analysis. I am happy to contribute this to the repo if you think it would be useful

**Comment by cdisselkoen** [comment]
> I really should not be using any of the function hooks

If you want to make sure that this is the case, you can start from [`Config::new()`](https://docs.rs/haybale/0.6.3/haybale/config/struct.Config.html#method.new) instead of `Config::default()` - that gives you a `Config` without the default hooks.

> I am happy to contribute this to the repo if you think it would be useful

Sure, I'm happy to take a PR on this.

**Comment by hudson-ayers** [comment]
One factor that seems to complicate this is calls to LLVM intrinsics. Intrinsics are hooked, so anything after the `Call` does not appear in the `Path`. And while I do not use any of the default function hooks, I inevitably use the intrinsic hooks -- this is basically unavoidable.

So a question: is a safe way to check whether a call will lead to a basic block being added to the Path to just check whether `resolve_function(&call.function) == ResolvedFunction::NoHookActive(_)`? (That is, NoHookActive == bb will be added to path for that call).

**Comment by cdisselkoen** [comment]
Yes, I believe that for your purposes the call will result in a path entry if and only if we have `NoHookActive`.  (You can see where `self.state.record_path_entry()` occurs in the code if you want to be more precise.)

Regarding intrinsics, I'll mention that it can be target-dependent in LLVM whether they actually end up being calls in the machine code or not.  Some LLVM backends will compile some intrinsics down to individual assembly instructions or assembly instruction sequences, in which case we wouldn't have a separate basic block for the intrinsic anyway.

**Comment by hudson-ayers** [comment]
> Yes, I believe that for your purposes the call will result in a path entry if and only if we have `NoHookActive`. (You can see where `self.state.record_path_entry()` occurs in the code if you want to be more precise.)
> 
> Regarding intrinsics, I'll mention that it can be target-dependent in LLVM whether they actually end up being calls in the machine code or not. Some LLVM backends will compile some intrinsics down to individual assembly instructions or assembly instruction sequences, in which case we wouldn't have a separate basic block for the intrinsic anyway.

Thanks! I'll have to look some more into how LLVM compiles intrinsics to machine code for ARM thumbv7, but I think for now this gives me everything I need.
