### ISSUE TITLE
C bindings

### ISSUE THREAD

**Issue by pgarba** [PLSysSec/haybale#6]
Hi,

are you planing to create some C/C++ bindings ? 
Would really like to integrate your tool into one of my projects.

Thanks,
Peter

**Comment by cdisselkoen** [comment]
Hi Peter,

I have no plans to create C/C++ bindings; I do most of my development in Rust code, and that's sufficient for my use cases.  However, if you're interested in creating C/C++ bindings, I would definitely consider including them in this repo if you wanted.

Thanks,
Craig

**Comment by cdisselkoen** [comment]
I'm going to go ahead and close this issue for now; feel free to reopen to continue discussion.
