### ISSUE TITLE
assert failures for code compiled for 32 bit platforms

### ISSUE THREAD

**Issue by hudson-ayers** [PLSysSec/haybale#7]
I have the following function in a rust program
```rust
#[no_mangle]    
pub fn handle_interrupt(&self) {
    unsafe {
        let ptr = 0x4000_8308 as *mut u32;
        ptr.write(0 as u32);
    }
}
```

This rust program is compiled for a 32 bit Arm Cortex-M4 MCU via `cargo rustc --target=thumbv7em-none-eabi --release -- --e
mit=llvm-ir --emit=llvm-bc`

I wrote the following haybale code to analyze this function:
```rust
    //...
    let em: ExecutionManager<BtorBackend> = symex_function("handle_interrupt", project, config);
    em.next()
```

Unfortunately, this code fails with the following error:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `32`,
 right: `64`', /home/hudson/.cargo/git/checkouts/haybale-12b18082e7030da8/695e1fa/src/state.rs:1085:17
```

I assume this has something to do with the target CPU having a different pointer width than the host CPU on which I am running my haybale analyses, as the same function works if I compile for my host machine. Any suggestions for how I can fix this? Or is haybale incompatible with analysis of code compiled for 32 bit platforms?

**Comment by cdisselkoen** [comment]
Haybale currently assumes that pointers are 64-bit.  I'm not sure how much work it would be to relax this assumption.  But for the moment, no, Haybale can't analyze code compiled for 32-bit platforms.

**Comment by cdisselkoen** [comment]
Looking into this briefly - off the top of your head do you know if there's a way to tell the pointer size from looking at the LLVM bitcode?  I think we could do it by parsing [`Module.data_layout`](https://cdisselkoen.github.io/llvm-ir/llvm_ir/module/struct.Module.html#structfield.data_layout) or [`Module.target_triple`](https://cdisselkoen.github.io/llvm-ir/llvm_ir/module/struct.Module.html#structfield.target_triple), but I'm wondering if there's an easier way.

**Comment by cdisselkoen** [comment]
For now, we could also just make the user tell us the pointer size as an extra parameter in `Config`; I'm tentatively going with that for now.  

I made a first stab at relaxing the pointer-is-64-bits assumption on the branch `32-bit-targets`.  Can you see if that fixes your problem?  (It's very possible I missed something and there will still be assertion failures or similar.)  You'll also need to use `SimpleMemoryBackend` instead of `BtorBackend` - but it's very possible `SimpleMemoryBackend` is just faster anyway, and it may become the default in the future (with some kind of rename).

**Comment by hudson-ayers** [comment]
Ah amazing, that branch does work! Thank you so much for looking into this! I plan to try to use Haybale to analyze a bunch of different functions in Tock (https://github.com/tock/tock), so I will let you know if I run into any assertion failures you may have missed on the first pass.

Re: parsing pointer size from bitcode, parsing `Module.data_layout` seems easiest -- this seems to work on the couple of files I tried it on (both generated by rustc):

```rust
/// Extracts the pointer width from an LLVM module, or returns a default of 64 bits
/// if the width is not specified.
fn get_ptr_size(module: &Module) -> u32 {
    let default = 64;
    let d = &module.data_layout;
    d.find("-p").map_or(default, |idx| {
        d.get(idx..).map_or(default, |substr| {
            substr.find(":").map_or(default, |colon_idx| {
                let start = colon_idx + idx + 1;
                d.get(start..start + 2).map_or(default, |ptr_width_str| {
                    ptr_width_str.parse::<u32>().unwrap_or(default)
                })
            })
        })
    })
}
```

**Comment by cdisselkoen** [comment]
Thanks for the function!  I've added it (with an ack to you) and incorporated the autodetection into `Project` creation.  If you'd be willing to test the latest version of the `32-bit-targets` branch I'd appreciate it!

**Comment by hudson-ayers** [comment]
The latest commit works! Thanks again

**Comment by cdisselkoen** [comment]
Awesome!  Will close this and merge the branch to master.
